name: CI

on:
  push:
    branches:
      - main  # 또는 master 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: 설치 의존성
      run: |
        npm install

    - name: 빌드
      run: |
        npm run build

    - name: 테스트 실행
      run: |
        npm test

    - name: 웹사이트 배포
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
